name: Deployment Pipeline

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true   # forces Node.js 24 for all actions

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

defaults:
  run:
    working-directory: ./bloglist-backend

jobs:
  test_and_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      
      - name: Install dependencies
        run: npm install

      - name: Check style (Lint)
        run: npm run lint

      - name: Run Backend Tests
        run: npm test
        env:
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
          SECRET: ${{ secrets.SECRET }}

  docker_build_and_push:
    runs-on: ubuntu-latest
    needs: test_and_lint
    steps:
      - uses: actions/checkout@v4

      - name: List Dockerfile
        run: |
          echo "Checking for Dockerfile in bloglist-backend..."
          ls -l ./bloglist-backend
          if [ ! -f ./bloglist-backend/Dockerfile ]; then
            echo "ERROR: Dockerfile not found!"
            exit 1
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./bloglist-backend
          file: ./bloglist-backend/Dockerfile
          load: true
          tags: blogstack-backend:test

      - name: Test Docker Image
        run: |
          docker run -d --name test-backend -p 3003:3003 blogstack-backend:test
          sleep 10
          curl -f http://localhost:3003 || exit 1
          docker stop test-backend
          docker rm test-backend

      - name: Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./bloglist-backend
          file: ./bloglist-backend/Dockerfile
          push: true
          tags: mikokeng/blogstack-backend:latest